import 'package:flutter/material.dart';

const kPrimary      = Color(0xFF6C63FF);
const kBg           = Color(0xFFF5F7FA);
const kCard         = Color(0xFFFFFFFF);
const kBorder       = Color(0xFFEEF0F4);
const kText         = Color(0xFF1A1D23);
const kMuted        = Color(0xFF9499A5);
const kSurface      = Color(0xFF1A1830);
const kSurface2     = Color(0xFF221F38);
const kAccent       = Color(0xFFFFC542);
const kGreen        = Color(0xFF2ECC71);
const kRed          = Color(0xFFFF5E5E);
const kTextMain     = Color(0xFFEEECFF);
const kTextSub      = Color(0xFF8B87B8);
const kPrimaryLight = Color(0xFFEEEDFF);
const kGreenBg      = Color(0xFFECFDF5);
const kRedBg        = Color(0xFFFEF2F2);
const kYellow       = Color(0xFFF59E0B);
const kPreparing    = Color(0xFFF59E0B);
const kPreparingBg  = Color(0xFFFFFBEB);
const kOnTheWay     = Color(0xFF3B82F6);
const kOnTheWayBg   = Color(0xFFEFF6FF);
const kDelivered    = Color(0xFF10B981);
const kDeliveredBg  = Color(0xFFECFDF5);
const kCancelled    = Color(0xFFEF4444);
const kCancelledBg  = Color(0xFFFEF2F2);