// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrfaC-Pur3u-opeqAqxCnQDDGZ5nwQo9E',
    appId: '1:340625622680:android:1ee8d87b7de054bb08b2ed',
    messagingSenderId: '340625622680',
    projectId: 'eat2beat-5adcf',
    storageBucket: 'eat2beat-5adcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDasvFv2v_CbhbAX1slk7L4bnUYyOfhaCU',
    appId: '1:340625622680:ios:b1031827496f98ba08b2ed',
    messagingSenderId: '340625622680',
    projectId: 'eat2beat-5adcf',
    storageBucket: 'eat2beat-5adcf.firebasestorage.app',
    androidClientId: '340625622680-9of24k38nag49a2kcbsk3gek2v1239tb.apps.googleusercontent.com',
    iosClientId: '340625622680-i9fe92gdibmntjt5uf1ihlq60uugt6lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eat2beat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDasvFv2v_CbhbAX1slk7L4bnUYyOfhaCU',
    appId: '1:340625622680:ios:b1031827496f98ba08b2ed',
    messagingSenderId: '340625622680',
    projectId: 'eat2beat-5adcf',
    storageBucket: 'eat2beat-5adcf.firebasestorage.app',
    androidClientId: '340625622680-9of24k38nag49a2kcbsk3gek2v1239tb.apps.googleusercontent.com',
    iosClientId: '340625622680-i9fe92gdibmntjt5uf1ihlq60uugt6lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eat2beat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvvmheUMW7GWyllXIHQJ6AerwrPHzZXgs',
    appId: '1:340625622680:web:069def80a447b6ca08b2ed',
    messagingSenderId: '340625622680',
    projectId: 'eat2beat-5adcf',
    authDomain: 'eat2beat-5adcf.firebaseapp.com',
    storageBucket: 'eat2beat-5adcf.firebasestorage.app',
    measurementId: 'G-K74RR9N4DD',
  );

}