// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANEaeltJP3kQul_ZdPdJPfD1wjXpeLZa8',
    appId: '1:23005301367:android:74a945568260240d3f1472',
    messagingSenderId: '23005301367',
    projectId: 'eat2beat-dcd40',
    storageBucket: 'eat2beat-dcd40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAohVeA2_idF9pZsHcQcaheJxW39sMHWPI',
    appId: '1:23005301367:ios:bfc35f740427bdd63f1472',
    messagingSenderId: '23005301367',
    projectId: 'eat2beat-dcd40',
    storageBucket: 'eat2beat-dcd40.firebasestorage.app',
    iosBundleId: 'com.example.eat2beat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAohVeA2_idF9pZsHcQcaheJxW39sMHWPI',
    appId: '1:23005301367:ios:bfc35f740427bdd63f1472',
    messagingSenderId: '23005301367',
    projectId: 'eat2beat-dcd40',
    storageBucket: 'eat2beat-dcd40.firebasestorage.app',
    iosBundleId: 'com.example.eat2beat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAz4nlFMJFeq3qCilhuOZhgq-bVSwhPNI',
    appId: '1:23005301367:web:1b3d9e3c2d07965b3f1472',
    messagingSenderId: '23005301367',
    projectId: 'eat2beat-dcd40',
    authDomain: 'eat2beat-dcd40.firebaseapp.com',
    storageBucket: 'eat2beat-dcd40.firebasestorage.app',
    measurementId: 'G-D4WX68JN0F',
  );
}
